version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Cloning repositories...
      - git clone https://github.com/madhukamath29/enterprise_repo.git /home/enterprise
      - git clone https://github.com/madhukamath29/demo-odoo17.git /home/demo-odoo17
      - git clone https://github.com/madhukamath29/INV-Repo.git /home/INV-Repo
      - echo Repositories cloned successfully...

  build:
    commands:
      - echo Merging code from enterprise_repo and demo-odoo17...
      - mkdir merged_code
      - cp -r /home/enterprise/* merged_code/
      - cp -r /home/demo-odoo17/* merged_code/
      - echo Merging INV-Repo branches...
      
      # Checkout and copy code from each inv-repo branch
      - cd /home/INV-Repo
      - git checkout third-party-addons
      - cp -r * /home/merged_code/
      - git checkout common-addons
      - cp -r * /home/merged_code/
      - git checkout dev-GST
      - cp -r custom-addons/ /home/merged_code/
      - git checkout Qa_GST
      - cp -r custom-addons/ /home/merged_code/
      - git checkout Prod_GST
      - cp -r custom-addons/ /home/merged_code/
      - ls -l /home/merged_code/
      - echo Code from inv-repo merged successfully...

  post_build:
    commands:
      - echo Preparing artifacts for deployment...
      - mkdir -p temp/test
      - cp -r /home/merged_code/* temp/test/
      - ls -l temp/test/
      - echo Artifacts ready for deployment....

