version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies...
      - sudo apt-get update
      - sudo apt-get install -y git

  pre_build:
    commands:
      - echo Cloning repositories...
      - git clone https://github.com/madhukamath29/enterprise_repo.git /home/enterprise
      - git clone https://github.com/madhukamath29/demo-odoo17.git /home/demo-odoo17
      - git clone https://github.com/madhukamath29/INV-Repo.git /home/INV-Repo
      - echo Repositories cloned successfully...

  build:
    commands:
      - echo Merging code from enterprise_repo and demo-odoo17...
      - mkdir merged_code
      - cp -r /home/enterprise/* merged_code/
      - cp -r /home/demo-odoo17/* merged_code/
      - echo Merging INV-Repo branches...

      # Checkout and copy code from each inv-repo branch
      - cd /home/INV-Repo
      - git checkout third-party-addons
      - cp -r third-party-addons-folder/ /home/merged_code/  # Copy the folder and its contents
      - echo "Contents of third-party-addons-folder:"
      - ls -l /home/merged_code/third-party-addons-folder/  # List the contents after copying

      - git checkout common-addons
      - cp -r common-addon-folder/ /home/merged_code/  # Copy the folder and its contents
      - echo "Contents of common-addon-folder:"
      - ls -l /home/merged_code/common-addon-folder/  # List the contents after copying

      - git checkout dev-gst
      - cp -r custom-addons/ /home/merged_code/  # Copy the folder and its contents
      - echo "Contents of custom-addons from dev-gst:"
      - ls -l /home/merged_code/custom-addons/  # List the contents after copying

      - git checkout qa-gst
      - cp -r custom-addons/ /home/merged_code/  # Copy the folder and its contents
      - echo "Contents of custom-addons from qa-gst:"
      - ls -l /home/merged_code/custom-addons/  # List the contents after copying

      - git checkout prod-gst
      - cp -r custom-addons/ /home/merged_code/  # Copy the folder and its contents
      - echo "Contents of custom-addons from prod-gst:"
      - ls -l /home/merged_code/custom-addons/  # List the contents after copying

      - ls -l /home/merged_code/
      - echo Code from inv-repo merged successfully...

  post_build:
    commands:
      - echo Preparing artifacts for deployment.....
      - mkdir -p temp/test
      - cp -r /home/merged_code/* temp/test/
      - ls -l temp/test/
      - echo Artifacts ready for deployment...
